// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GETMATCHLASTINDEX_H_
#define FLATBUFFERS_GENERATED_GETMATCHLASTINDEX_H_

#include "flatbuffers/flatbuffers.h"

struct GetMatchLastIndexRequest;
struct GetMatchLastIndexRequestBuilder;

struct GetMatchLastIndexRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
    typedef GetMatchLastIndexRequestBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE { VT_KEYS = 4 };
    const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *keys() const {
        return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(
            VT_KEYS);
    }
    bool Verify(flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_KEYS) &&
               verifier.VerifyVector(keys()) && verifier.VerifyVectorOfStrings(keys()) &&
               verifier.EndTable();
    }
};

struct GetMatchLastIndexRequestBuilder {
    typedef GetMatchLastIndexRequest Table;
    flatbuffers::FlatBufferBuilder &fbb_;
    flatbuffers::uoffset_t start_;
    void add_keys(
        flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> keys) {
        fbb_.AddOffset(GetMatchLastIndexRequest::VT_KEYS, keys);
    }
    explicit GetMatchLastIndexRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<GetMatchLastIndexRequest> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = flatbuffers::Offset<GetMatchLastIndexRequest>(end);
        return o;
    }
};

inline flatbuffers::Offset<GetMatchLastIndexRequest> CreateGetMatchLastIndexRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> keys = 0) {
    GetMatchLastIndexRequestBuilder builder_(_fbb);
    builder_.add_keys(keys);
    return builder_.Finish();
}

inline flatbuffers::Offset<GetMatchLastIndexRequest> CreateGetMatchLastIndexRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *keys = nullptr) {
    auto keys__ = keys ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*keys) : 0;
    return CreateGetMatchLastIndexRequest(_fbb, keys__);
}

inline const GetMatchLastIndexRequest *GetGetMatchLastIndexRequest(const void *buf) {
    return flatbuffers::GetRoot<GetMatchLastIndexRequest>(buf);
}

inline const GetMatchLastIndexRequest *GetSizePrefixedGetMatchLastIndexRequest(const void *buf) {
    return flatbuffers::GetSizePrefixedRoot<GetMatchLastIndexRequest>(buf);
}

inline bool VerifyGetMatchLastIndexRequestBuffer(flatbuffers::Verifier &verifier) {
    return verifier.VerifyBuffer<GetMatchLastIndexRequest>(nullptr);
}

inline bool VerifySizePrefixedGetMatchLastIndexRequestBuffer(flatbuffers::Verifier &verifier) {
    return verifier.VerifySizePrefixedBuffer<GetMatchLastIndexRequest>(nullptr);
}

inline void FinishGetMatchLastIndexRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<GetMatchLastIndexRequest> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedGetMatchLastIndexRequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<GetMatchLastIndexRequest> root) {
    fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_GETMATCHLASTINDEX_H_
