// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_LOCALMETA_H_
#define FLATBUFFERS_GENERATED_LOCALMETA_H_

#include "flatbuffers/flatbuffers.h"

struct Block;
struct BlockBuilder;

struct LocalMeta;
struct LocalMetaBuilder;

struct Block FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
    typedef BlockBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE { VT_KEY = 4, VT_OFFSET = 6 };
    const flatbuffers::String *key() const {
        return GetPointer<const flatbuffers::String *>(VT_KEY);
    }
    uint64_t offset() const { return GetField<uint64_t>(VT_OFFSET, 0); }
    bool Verify(flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_KEY) &&
               verifier.VerifyString(key()) && VerifyField<uint64_t>(verifier, VT_OFFSET) &&
               verifier.EndTable();
    }
};

struct BlockBuilder {
    typedef Block Table;
    flatbuffers::FlatBufferBuilder &fbb_;
    flatbuffers::uoffset_t start_;
    void add_key(flatbuffers::Offset<flatbuffers::String> key) {
        fbb_.AddOffset(Block::VT_KEY, key);
    }
    void add_offset(uint64_t offset) { fbb_.AddElement<uint64_t>(Block::VT_OFFSET, offset, 0); }
    explicit BlockBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<Block> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = flatbuffers::Offset<Block>(end);
        return o;
    }
};

inline flatbuffers::Offset<Block> CreateBlock(flatbuffers::FlatBufferBuilder &_fbb,
                                              flatbuffers::Offset<flatbuffers::String> key = 0,
                                              uint64_t offset = 0) {
    BlockBuilder builder_(_fbb);
    builder_.add_offset(offset);
    builder_.add_key(key);
    return builder_.Finish();
}

inline flatbuffers::Offset<Block> CreateBlockDirect(flatbuffers::FlatBufferBuilder &_fbb,
                                                    const char *key = nullptr,
                                                    uint64_t offset = 0) {
    auto key__ = key ? _fbb.CreateString(key) : 0;
    return CreateBlock(_fbb, key__, offset);
}

struct LocalMeta FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
    typedef LocalMetaBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
        VT_IPC_HANDLE = 4,
        VT_BLOCK_SIZE = 6,
        VT_BLOCKS = 8
    };
    const flatbuffers::Vector<uint8_t> *ipc_handle() const {
        return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_IPC_HANDLE);
    }
    int32_t block_size() const { return GetField<int32_t>(VT_BLOCK_SIZE, 0); }
    const flatbuffers::Vector<flatbuffers::Offset<Block>> *blocks() const {
        return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Block>> *>(VT_BLOCKS);
    }
    bool Verify(flatbuffers::Verifier &verifier) const {
        return VerifyTableStart(verifier) && VerifyOffset(verifier, VT_IPC_HANDLE) &&
               verifier.VerifyVector(ipc_handle()) &&
               VerifyField<int32_t>(verifier, VT_BLOCK_SIZE) && VerifyOffset(verifier, VT_BLOCKS) &&
               verifier.VerifyVector(blocks()) && verifier.VerifyVectorOfTables(blocks()) &&
               verifier.EndTable();
    }
};

struct LocalMetaBuilder {
    typedef LocalMeta Table;
    flatbuffers::FlatBufferBuilder &fbb_;
    flatbuffers::uoffset_t start_;
    void add_ipc_handle(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ipc_handle) {
        fbb_.AddOffset(LocalMeta::VT_IPC_HANDLE, ipc_handle);
    }
    void add_block_size(int32_t block_size) {
        fbb_.AddElement<int32_t>(LocalMeta::VT_BLOCK_SIZE, block_size, 0);
    }
    void add_blocks(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Block>>> blocks) {
        fbb_.AddOffset(LocalMeta::VT_BLOCKS, blocks);
    }
    explicit LocalMetaBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) {
        start_ = fbb_.StartTable();
    }
    flatbuffers::Offset<LocalMeta> Finish() {
        const auto end = fbb_.EndTable(start_);
        auto o = flatbuffers::Offset<LocalMeta>(end);
        return o;
    }
};

inline flatbuffers::Offset<LocalMeta> CreateLocalMeta(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ipc_handle = 0, int32_t block_size = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Block>>> blocks = 0) {
    LocalMetaBuilder builder_(_fbb);
    builder_.add_blocks(blocks);
    builder_.add_block_size(block_size);
    builder_.add_ipc_handle(ipc_handle);
    return builder_.Finish();
}

inline flatbuffers::Offset<LocalMeta> CreateLocalMetaDirect(
    flatbuffers::FlatBufferBuilder &_fbb, const std::vector<uint8_t> *ipc_handle = nullptr,
    int32_t block_size = 0, const std::vector<flatbuffers::Offset<Block>> *blocks = nullptr) {
    auto ipc_handle__ = ipc_handle ? _fbb.CreateVector<uint8_t>(*ipc_handle) : 0;
    auto blocks__ = blocks ? _fbb.CreateVector<flatbuffers::Offset<Block>>(*blocks) : 0;
    return CreateLocalMeta(_fbb, ipc_handle__, block_size, blocks__);
}

inline const LocalMeta *GetLocalMeta(const void *buf) {
    return flatbuffers::GetRoot<LocalMeta>(buf);
}

inline const LocalMeta *GetSizePrefixedLocalMeta(const void *buf) {
    return flatbuffers::GetSizePrefixedRoot<LocalMeta>(buf);
}

inline bool VerifyLocalMetaBuffer(flatbuffers::Verifier &verifier) {
    return verifier.VerifyBuffer<LocalMeta>(nullptr);
}

inline bool VerifySizePrefixedLocalMetaBuffer(flatbuffers::Verifier &verifier) {
    return verifier.VerifySizePrefixedBuffer<LocalMeta>(nullptr);
}

inline void FinishLocalMetaBuffer(flatbuffers::FlatBufferBuilder &fbb,
                                  flatbuffers::Offset<LocalMeta> root) {
    fbb.Finish(root);
}

inline void FinishSizePrefixedLocalMetaBuffer(flatbuffers::FlatBufferBuilder &fbb,
                                              flatbuffers::Offset<LocalMeta> root) {
    fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_LOCALMETA_H_
